[project]
name = "jike-spider"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
start = "python jike.py"
ref = "python refresh.py"
desame = 'python .\depulicate.py'
fmt = "ruff format ."
lint = "ruff lint --fix ."
style = { depends_on = ["fmt", "lint"] }
[dependencies]
lxml = ">=5.1.0,<5.2"
requests = ">=2.31.0,<2.32"
python = ">=3.12.1,<3.13"
selenium = ">=4.16.0,<4.17"
firefox = ">=121.0,<122"
ruff = ">=0.1.13,<0.2"
pylint = ">=3.0.3,<3.1"
